### ISSUE TITLE
Fail if there's imports of the form `import library.submodule` (which can't be rewritten)

### ISSUE THREAD

**Issue by thedrow** [pradyunsg/vendoring#15] opened 2020-10-04 11:20 UTC
I tried to vendor httpx and got the following result:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-954d8b9af18d> in <module>
----> 1 from pip._vendor import httpx

~/Documents/Projects/pip/src/pip/_vendor/httpx/__init__.py in <module>
      1 from .__version__ import __description__, __title__, __version__
----> 2 from ._api import delete, get, head, options, patch, post, put, request, stream
      3 from ._auth import Auth, BasicAuth, DigestAuth
      4 from ._client import AsyncClient, Client
      5 from ._config import Limits, Proxy, Timeout, create_ssl_context

~/Documents/Projects/pip/src/pip/_vendor/httpx/_api.py in <module>
      1 import typing
      2
----> 3 from ._client import Client, StreamContextManager
      4 from ._config import DEFAULT_TIMEOUT_CONFIG
      5 from ._models import Request, Response

~/Documents/Projects/pip/src/pip/_vendor/httpx/_client.py in <module>
      8
      9 from .__version__ import __version__
---> 10 from ._auth import Auth, BasicAuth, FunctionAuth
     11 from ._config import (
     12     DEFAULT_LIMITS,

~/Documents/Projects/pip/src/pip/_vendor/httpx/_auth.py in <module>
      8
      9 from ._exceptions import ProtocolError
---> 10 from ._models import Request, Response
     11 from ._utils import to_bytes, to_str, unquote
     12

~/Documents/Projects/pip/src/pip/_vendor/httpx/_models.py in <module>
     11
     12 from pip._vendor import rfc3986
---> 13 import rfc3986.exceptions
     14
     15 from ._content import PlainByteStream, encode_request, encode_response

ModuleNotFoundError: No module named 'rfc3986'
```

**Comment by pradyunsg** [comment] 2020-10-04 17:49
See https://github.com/pradyunsg/vendoring/issues/14#issuecomment-703290689

**Comment by jku** [comment] 2020-10-07 11:19
` import rfc3986.exceptions`

The issue here is that this type of import cannot be automatically handled by vendoring as `from pip._vendor import rfc3986.exceptions` would be invalid. `from pip._vendor.rfc3986 import exceptions` would work but then the code would break because `rfc3986.exceptions` is no longer defined.

I'm facing this same problem in TUF and securesystemslib. It looks like I have to rewrite a whole bunch of `import package.module`-style imports to make them work with `vendoring`...

**Comment by thedrow** [comment] 2020-10-07 12:03
I tried to add httpx to pip for a patch I'm working on.
I had to manually include a rewrite rule for this kind of import.
Instead, it should be transformed into `import pip._vendor.rfc3986.exceptions` automatically.

**Comment by jku** [comment] 2020-10-07 12:15
> Instead, it should be transformed into `import pip._vendor.rfc3986.exceptions` automatically.

Your suggestion adds a completely new local name to be defined (something vendoring does not do currently) ... what happens next? should vendoring modify all of the code that uses the old `rfc3986.exceptions` local name to instead use `pip._vendor.rfc3986.exceptions`? That kind of patching sounds dangerous.

**Comment by thedrow** [comment] 2020-10-07 12:51
But if we don't, using the vendored httpx becomes impossible unless you add a manual substitution.

**Comment by pradyunsg** [comment] 2020-10-07 14:12
Again, please provide a reproducer for the issue you're reporting. I'd requested for the same in #14 as well.

Everything you've said thus far isn't enough to clearly understand what input is being given to this tool, what behavior you're seeing, and what behavior you're expecting.

**Comment by jku** [comment] 2020-10-07 14:19
> Everything you've said thus far isn't enough to clearly understand what input is being given to this tool, what behavior you're seeing, and what behavior you're expecting.

So the issue is that this style of import does not get "prefixed" by vendoring:
`import package.module`
(where `package` may be the vendored package itself or another vendored package)
As a result 

I have a runnable example here (see README for reproduction instructions): https://gist.github.com/jku/22d5f08083c8b7b2f3e552f7ca6c301e

**Comment by pradyunsg** [comment] 2020-10-09 09:30
Thanks for the reproducer! That helps a lot.

And yes, this is 100% a bug! The regex for matching `import xyz` doesn't consider the possibility of `import xyz.abc` -- which is wrong. :)


https://github.com/pradyunsg/vendoring/blob/a0d250d090a2e18aea075728a37da118064553e9/src/vendoring/tasks/vendor.py#L63-L64

**Comment by jku** [comment] 2020-10-09 10:16
You're welcome, thanks for looking into this!

That regex does seem to be the issue yes. I don't see any non-hacky way for vendoring to fix this though. Do you?

(the hacky ways would involve e.g. creating a dummy `xyz` object and the assigning the result of  `from xyz import abc as _vendoring_abc` to the attribute `xyz.abc` )

**Comment by jku** [comment] 2020-10-09 10:31
By the way: I'm willing to do some work on this if you think this could be fixed in vendoring -- this would save me a lot of trouble in tuf and securesystemslib :)

**Comment by pradyunsg** [comment] 2020-10-09 10:45
> Do you?

Nope. :(

I'm not super excited by the idea of introducing any hacks here. I don't think there's much that can be done to handle this in a non-fragile manner.

---

TBH, I'm now thinking more along the lines of "`vendoring` should fail instead of having a form that'll pass through without changes and fail later." :/

**Closed** 2021-09-11 22:21 UTC
Labels: bug
